name: Release & Publish (npm)

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  id-token: write
  packages: read

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install deps
        run: npm ci || npm i

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Publish to npm (provenance)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public --provenance

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
